# Generated by Django 5.1.6 on 2025-03-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioLokiiapp', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel( 
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='projects/files/')),
                ('image_file', models.ImageField(upload_to='projects/images/')),
            ],
        ),
    ]
